"""add cascade delete to likes

Revision ID: 2e93ff8fa58f
Revises: c34f82581520
Create Date: 2026-07-29 12:42:43.462551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e93ff8fa58f'
down_revision: Union[str, Sequence[str], None] = 'c34f82581520'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('likes_user_id_fkey'), 'likes', type_='foreignkey')
    op.drop_constraint(op.f('likes_note_id_fkey'), 'likes', type_='foreignkey')
    op.create_foreign_key(
    "likes_note_id_fkey",
    "likes",
    "notes",
    ["note_id"],
    ["id"],
    ondelete="CASCADE",)

    op.create_foreign_key(
    "likes_user_id_fkey",
    "likes",
    "users",
    ["user_id"],
    ["id"],
    ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("likes_note_id_fkey", 'likes', type_='foreignkey')
    op.drop_constraint("likes_user_id_fkey", 'likes', type_='foreignkey')
    op.create_foreign_key(op.f('likes_note_id_fkey'), 'likes', 'notes', ['note_id'], ['id'])
    op.create_foreign_key(op.f('likes_user_id_fkey'), 'likes', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
